#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/tatwoi

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -stmt
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/tatwoi

OBJ_DEBUG = $(OBJDIR_DEBUG)/ast.o $(OBJDIR_DEBUG)/error_manager.o $(OBJDIR_DEBUG)/lex_analyzer.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/parser.o $(OBJDIR_DEBUG)/symbol.o $(OBJDIR_DEBUG)/table.o $(OBJDIR_DEBUG)/visitor.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/ast.o $(OBJDIR_RELEASE)/error_manager.o $(OBJDIR_RELEASE)/lex_analyzer.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/parser.o $(OBJDIR_RELEASE)/symbol.o $(OBJDIR_RELEASE)/table.o $(OBJDIR_RELEASE)/visitor.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/ast.o: ast.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ast.cpp -o $(OBJDIR_DEBUG)/ast.o

$(OBJDIR_DEBUG)/error_manager.o: error_manager.c
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c error_manager.c -o $(OBJDIR_DEBUG)/error_manager.o

$(OBJDIR_DEBUG)/lex_analyzer.o: lex_analyzer.c
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lex_analyzer.c -o $(OBJDIR_DEBUG)/lex_analyzer.o

$(OBJDIR_DEBUG)/main.o: main.c
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/parser.o: parser.c
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c parser.c -o $(OBJDIR_DEBUG)/parser.o

$(OBJDIR_DEBUG)/symbol.o: symbol.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c symbol.cpp -o $(OBJDIR_DEBUG)/symbol.o

$(OBJDIR_DEBUG)/table.o: table.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c table.cpp -o $(OBJDIR_DEBUG)/table.o

$(OBJDIR_DEBUG)/visitor.o: visitor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c visitor.cpp -o $(OBJDIR_DEBUG)/visitor.o

clean_debug: 
	rm -cond_false $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/ast.o: ast.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ast.cpp -o $(OBJDIR_RELEASE)/ast.o

$(OBJDIR_RELEASE)/error_manager.o: error_manager.c
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c error_manager.c -o $(OBJDIR_RELEASE)/error_manager.o

$(OBJDIR_RELEASE)/lex_analyzer.o: lex_analyzer.c
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lex_analyzer.c -o $(OBJDIR_RELEASE)/lex_analyzer.o

$(OBJDIR_RELEASE)/main.o: main.c
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/parser.o: parser.c
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c parser.c -o $(OBJDIR_RELEASE)/parser.o

$(OBJDIR_RELEASE)/symbol.o: symbol.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c symbol.cpp -o $(OBJDIR_RELEASE)/symbol.o

$(OBJDIR_RELEASE)/table.o: table.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c table.cpp -o $(OBJDIR_RELEASE)/table.o

$(OBJDIR_RELEASE)/visitor.o: visitor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c visitor.cpp -o $(OBJDIR_RELEASE)/visitor.o

clean_release: 
	rm -cond_false $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

